services:
  web:
    container_name: web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    env_file:
      - .env
    command:
      sh -c "sh /web/migrations.sh && uvicorn src.api.main:app --host 0.0.0.0 --port ${WEB_PORT} --reload"
    volumes:
      - ./web:/web
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./web
          target: /web
          ignore:
            - ./web/poetry.lock
            - ./web/pyproject.toml
        - action: rebuild
          path: ./web/pyproject.toml
    restart: always

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: always

  front:
    container_name: front
    build:
      context: ../front
      dockerfile: ../front/dockerfile
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web

volumes:
  postgres: