"""genre create table

Revision ID: 0d2b7897b1f7
Revises: 408d5e76470a
Create Date: 2025-03-01 08:43:35.276221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2b7897b1f7'
down_revision: Union[str, None] = '408d5e76470a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    genre = op.create_table('genre',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
        sa.Column('name', sa.VARCHAR(length=128), nullable=False, comment='Название жанра'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.bulk_insert(
        genre,
        [
            {'name': 'Сказка'},
            {'name': 'Фэнтези'},
            {'name': 'Детектив'},
            {'name': 'Роман'},
            {'name': 'Научная фантастика'},
            {'name': 'Ужасы'},
            {'name': 'Исторический роман'},
            {'name': 'Биография'},
            {'name': 'Приключения'},
            {'name': 'Комедия'},
            {'name': 'Драма'},
            {'name': 'Триллер'},
            {'name': 'Поэзия'},
            {'name': 'Документальная литература'},
            {'name': 'Мистика'},
            {'name': 'Киберпанк'},
            {'name': 'Психология'},
            {'name': 'Философия'},
            {'name': 'Эротика'},
            {'name': 'Готика'},
            {'name': 'Антиутопия'},
            {'name': 'Военная проза'},
            {'name': 'Магический реализм'},
            {'name': 'Любовный роман'},
            {'name': 'Спорт'},
            {'name': 'Хоррор'},
            {'name': 'Политическая литература'},
            {'name': 'Постапокалипсис'},
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    # ### end Alembic commands ###
