"""user create table

Revision ID: 29332d846efb
Revises: 
Create Date: 2025-02-22 09:33:38.150270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_extension import PGExtension
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '29332d846efb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный ID'),
        sa.Column('first_name', sa.VARCHAR(length=25), nullable=True, comment='Имя пользователя'),
        sa.Column('last_name', sa.VARCHAR(length=50), nullable=True, comment='Фамилия пользователя'),
        sa.Column('second_name', sa.VARCHAR(length=25), nullable=True, comment='Отчество пользователя'),
        sa.Column('email', sa.VARCHAR(length=60), nullable=False, comment='Почта пользователя'),
        sa.Column('username', sa.VARCHAR(length=20), nullable=False, comment='Псевдоним пользователя'),
        sa.Column('password', sa.VARCHAR(length=60), nullable=False, comment='SHA256 пароля пользователя'),
        sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='Подтверждается ссылкой на почте'),
        sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='Заблокирован ли пользователь'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    public_pgcrypto = PGExtension(
        schema="public",
        signature="pgcrypto"
    )
    op.create_entity(public_pgcrypto)  # type: ignore

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_pgcrypto = PGExtension(
        schema="public",
        signature="pgcrypto"
    )
    op.drop_entity(public_pgcrypto)  # type: ignore

    op.drop_table('user')
    # ### end Alembic commands ###
