"""maker, taker create tables

Revision ID: 3a3ebbaa2f77
Revises: 66b0e28ff85e
Create Date: 2025-03-02 11:17:56.825982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3ebbaa2f77'
down_revision: Union[str, None] = '66b0e28ff85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maker',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('book_id', sa.UUID(), nullable=False, comment='ID книги'),
    sa.Column('track_number', sa.VARCHAR(length=48), nullable=True, comment='Номер отслеживания посылки'),
    sa.Column('is_received', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='Подтверждение получения книги'),
    sa.Column('is_accepted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='Подтверждение начала обмена'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taker',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя'),
    sa.Column('book_id', sa.UUID(), nullable=False, comment='ID книги'),
    sa.Column('track_number', sa.VARCHAR(length=48), nullable=True, comment='Номер отслеживания посылки'),
    sa.Column('is_received', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False, comment='Подтверждение получения книги'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id'], ['maker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user_address', 'mail_index',
               existing_type=sa.VARCHAR(length=6),
               comment='Почтовый индекс',
               existing_comment='Название книги',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_address', 'mail_index',
               existing_type=sa.VARCHAR(length=6),
               comment='Название книги',
               existing_comment='Почтовый индекс',
               existing_nullable=False)
    op.drop_table('taker')
    op.drop_table('maker')
    # ### end Alembic commands ###
