"""book, author, book_genre create tables

Revision ID: 57ceef70767a
Revises: 0d2b7897b1f7
Create Date: 2025-03-01 10:39:20.314085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ceef70767a'
down_revision: Union[str, None] = '0d2b7897b1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный ID'),
        sa.Column('first_name', sa.VARCHAR(length=48), nullable=True, comment='Имя автора'),
        sa.Column('last_name', sa.VARCHAR(length=48), nullable=True, comment='Фамилия автора'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный ID'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='ID владельца книги'),
        sa.Column('author_id', sa.UUID(), nullable=False, comment='ID автора'),
        sa.Column('name', sa.VARCHAR(length=128), nullable=False, comment='Название книги'),
        sa.Column('isbn', sa.VARCHAR(length=13), nullable=False, comment='ISBN номер книги'),
        sa.Column('published_year', sa.VARCHAR(length=4), nullable=False, comment='Год публикации книги'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_genre',
        sa.Column('book_id', sa.UUID(), nullable=False, comment='ID книги'),
        sa.Column('genre_id', sa.Integer(), nullable=False, comment='ID жанра'),
        sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
        sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
        sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
