"""user_address create inactive_else_user_address_trigger

Revision ID: 66b0e28ff85e
Revises: 90ae42d7021e
Create Date: 2025-03-01 22:42:39.993341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '66b0e28ff85e'
down_revision: Union[str, None] = '90ae42d7021e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_inactive_else_user_address_function = PGFunction(
        schema="public",
        signature="inactive_else_user_address_function()",
        definition='RETURNS TRIGGER AS $$\n    DECLARE\n        active_count INT;\n    BEGIN\n        IF OLD.is_active = TRUE AND NEW.is_active = TRUE THEN\n            RETURN NEW;\n        END IF;\n\n        SELECT COUNT(*) INTO active_count \n        FROM public.user_address \n        WHERE public.user_address.is_active = TRUE AND public.user_address.id <> NEW.id;\n\n        IF NEW.is_active = TRUE THEN\n            UPDATE public.user_address\n            SET is_active = FALSE\n            WHERE public.user_address.is_active = TRUE AND public.user_address.id <> NEW.id;\n\n        ELSE\n            IF active_count = 0 THEN\n                NEW.is_active := TRUE;\n            END IF;\n        END IF;\n\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql'
    )
    op.create_entity(public_inactive_else_user_address_function)

    public_user_address_inactive_else_user_address_trigger = PGTrigger(
        schema="public",
        signature="inactive_else_user_address_trigger",
        on_entity="public.user_address",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE ON user_address\n        FOR EACH ROW\n        WHEN (pg_trigger_depth() = 0)\n        EXECUTE FUNCTION public.inactive_else_user_address_function()'
    )
    op.create_entity(public_user_address_inactive_else_user_address_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_user_address_inactive_else_user_address_trigger = PGTrigger(
        schema="public",
        signature="inactive_else_user_address_trigger",
        on_entity="public.user_address",
        is_constraint=False,
        definition='BEFORE INSERT OR UPDATE ON user_address\n        FOR EACH ROW\n        WHEN (pg_trigger_depth() = 0)\n        EXECUTE FUNCTION public.inactive_else_user_address_function()'
    )
    op.drop_entity(public_user_address_inactive_else_user_address_trigger)

    public_inactive_else_user_address_function = PGFunction(
        schema="public",
        signature="inactive_else_user_address_function()",
        definition='RETURNS TRIGGER AS $$\n    DECLARE\n        active_count INT;\n    BEGIN\n        IF OLD.is_active = TRUE AND NEW.is_active = TRUE THEN\n            RETURN NEW;\n        END IF;\n\n        SELECT COUNT(*) INTO active_count \n        FROM public.user_address \n        WHERE public.user_address.is_active = TRUE AND public.user_address.id <> NEW.id;\n\n        IF NEW.is_active = TRUE THEN\n            UPDATE public.user_address\n            SET is_active = FALSE\n            WHERE public.user_address.is_active = TRUE AND public.user_address.id <> NEW.id;\n\n        ELSE\n            IF active_count = 0 THEN\n                NEW.is_active := TRUE;\n            END IF;\n        END IF;\n\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql'
    )
    op.drop_entity(public_inactive_else_user_address_function)

    # ### end Alembic commands ###
