"""user_address create table

Revision ID: 90ae42d7021e
Revises: 630d9f743a1b
Create Date: 2025-03-01 22:41:41.690824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ae42d7021e'
down_revision: Union[str, None] = '630d9f743a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_address',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный ID'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='ID владельца книги'),
        sa.Column('mail_index', sa.VARCHAR(length=6), nullable=False, comment='Название книги'),
        sa.Column('city', sa.VARCHAR(length=128), nullable=False, comment='Название города'),
        sa.Column('street', sa.VARCHAR(length=128), nullable=False, comment='Название улицы'),
        sa.Column('house', sa.VARCHAR(length=128), nullable=True, comment='Номер дома'),
        sa.Column('build', sa.VARCHAR(length=128), nullable=True, comment='Номер строения'),
        sa.Column('apartment', sa.VARCHAR(length=128), nullable=False, comment='Номер квартиры'),
        sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активность адреса'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_address')
    # ### end Alembic commands ###
